ARG build_env="dev"

FROM python:3.12.1-alpine3.18 AS base
WORKDIR /app
RUN pip install --upgrade pip
COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN apk add --no-cache redis

FROM base AS branch-dev
RUN apk add --no-cache curl htop

FROM base AS branch-prod
COPY ./ /app/

FROM branch-${build_env} AS final
EXPOSE 5000
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "catalog_app:CatalogApp().app"]