# Use a lightweight Python image
FROM python:3.9-alpine

# Set the working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the source code into the container
COPY . .

# Expose Flask app port
EXPOSE 5000

# Use Gunicorn for better process management
CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:5000", "catalog_app:app"]
